### ISSUE TITLE
I got some errors when using this code to evaluate davis-2016

### ISSUE THREAD

**Issue by qyz55** [fperazzi/davis-2017#1]
Hello, I am new to DAVIS dataset. Recently I need to evaluate the performance of an algorithm on DAVIS-2016, and I notice that the document of this code have the parameter “--year 2016”. But when I run eval.py, results are as below:(I'm on windows 10 instead of Linux, perhapas it matters)

[WARNING][20-09-2017 19:39:44] Temporal stability not available
[INFO][20-09-2017 19:39:44] Loading DAVIS year: 2016 phase: phase.VAL
[INFO][20-09-2017 19:39:44] Loading video segmentations from: D:\Code\OSVOS-TensorFlow\DAVIS\Results\Segmentations\480p\OSVOS
[INFO][20-09-2017 19:39:45] Evaluating measure: J
D:\Software\Python3\lib\site-packages\numpy\core\fromnumeric.py:2909: RuntimeWarning: Mean of empty slice. out=out, **kwargs)
D:\Software\Python3\lib\site-packages\numpy\core\_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
[INFO][20-09-2017 19:39:45] Evaluating measure: F
+--------+--------+----------+---------+--------+----------+---------+
| Method | J_mean | J_recall | J_decay | F_mean | F_recall | F_decay |
+--------+--------+----------+---------+--------+----------+---------+
| OSVOS  |  nan   |   nan    |   nan   |  nan   |   nan    |   nan   |
+--------+--------+----------+---------+--------+----------+---------+

[INFO][20-09-2017 19:39:45] Saving output in: results.yaml

Then I debug the code. I notice that function "_get_num_objects" in base.py always return 0. And I read the code. It seems to return 0 when there are only 255 and 0 in a picture(255 is taken as unknown label, and 0 is taken as background). It works well in davis-2017 for label in davis-2017 is not signed by number 255. Howerer, davis-2016 annotations picture only have number 255 and 0 in it. I guess that may be the cause of my failure, so I try to delete the code "ids = ids[:-1] if ids[-1] == 255 else ids". But then all the results become 100%. I don't know what can I do then. If you know what to do, please tell me. Thanks.

**Comment by fperazzi** [comment]
`D:\Software\Python3\lib\site-packages\numpy\core\fromnumeric.py:2909: RuntimeWarning: Mean of empty slice. out=out, **kwargs)`

Looks like it's trying to slice an empty array. Could you check if the images are loaded correctly?

**Comment by qyz55** [comment]
Oh I get to the point. It just because I forgot to add parameter "--single-object" while davis-2016 all has just one object in a picture.
