### ISSUE TITLE
cannot find package according to requirement.txt

### ISSUE THREAD

**Issue by asimay** [fperazzi/davis-2017#11]
ResolvePackageNotFound:
  - easydict ==1.7

Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...................

ResolvePackageNotFound:
  - functools32 ==3.2.3.post2

**Comment by fperazzi** [comment]
Install pip within your conda environmet: conda install pip and use the
locally installed pip to install easydict: pip install easydict.
