### ISSUE TITLE
ValueError: cannot reshape array of size 1 into shape (3)

### ISSUE THREAD

**Issue by du0915** [fperazzi/davis-2017#12]
Hello, I am new to DAVIS dataset. When I run this commad 
python python/tools/eval.py -i /... -o results.yaml --year 2016 --single-object --phase val
Results in:
Traceback (most recent call last):
  File "python/tools/eval.py", line 80, in <module>
    osp.join(args.input,s),args.single_object) for s in db.iternames()]
  File "/home/zhaolei/workspace/davis-2017/python/lib/davis/dataset/base.py", line 127, in __init__
    self.n_objects = _get_num_objects(self[0])
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/collection.py", line 264, in __getitem__
    self.data[idx] = self.load_func(fname, **kwargs)
  File "/home/zhaolei/workspace/davis-2017/python/lib/davis/dataset/base.py", line 27, in _load_annotation
    annotation,_ = imread_indexed(filename)
  File "/home/zhaolei/workspace/davis-2017/python/lib/davis/misc/io.py", line 13, in imread_indexed
    return annotation,np.array(im.getpalette()).reshape((-1,3))
ValueError: cannot reshape array of size 1 into shape (3)
How can I solve it? 
Thank you.

**Comment by fperazzi** [comment]
There is a problem with `im.getpalette()`. Are the images you are reading indexed PNGs?

**Comment by SreenivasVRao** [comment]
Hi, I'm running in to this same problem. Any advice on why that might happen?

**Comment by fperazzi** [comment]
You have a problem reading the image palette. Are you saving indexed png's?

Best,
Federico

**Comment by SreenivasVRao** [comment]
Hi @fperazzi , yes I am. My results are saved on disk as results/blackswan/00000.png, 00001.png and so on.

The PNGs are 3 channels when I open with skimage.io, and they're binary masks for the 2016 challenge.

**Comment by fperazzi** [comment]
Replace your results with the ground truth images. Do you have the same
error?

**Comment by SreenivasVRao** [comment]
I tried that. That gives all perfect scores.

**Comment by fperazzi** [comment]
So you are not saving an indexed PNG. Check out in the code, we provide a
function to save results.

**Comment by SreenivasVRao** [comment]
Oh I see. All right I'll try that. I've been using cv2.imwrite() to save the images. Thanks!

**Comment by fperazzi** [comment]
Yes, cv2.imwrite won't work.
