### ISSUE TITLE
for s in self._db_sequences result is empty 

### ISSUE THREAD

**Issue by EternityZY** [fperazzi/davis-2017#13]
The code in python/davis/dataset/loader.py
self._db_sequences = db_read_sequences(year,self._phase)

    # Load sequences
    self.sequences = [Sequence(s.name)
        for s in self._db_sequences]

    # Load sequences
    self.annotations = [Annotation(s.name,self._single_object)
        for s in self._db_sequences]

    self._keys = dict(zip([s.name for s in self.sequences],
      range(len(self.sequences))))

When I run python/experiments/visualize.py ,I find 
self.sequences = [Sequence(s.name)
        for s in self._db_sequences]
can get a result list,

but,
 # Load sequences
    self.annotations = [Annotation(s.name,self._single_object)
        for s in self._db_sequences]
the result list is empty.
This led to the code in  python/experiments/visualize.py
db = DAVISLoader(year=cfg.YEAR,phase=cfg.PHASE)
im = overlay(db[0].images[0],db[0].annotations[0],db.color_palette)
db is empty.
Is it a mistake in my operation or a bug in the code itself, I hope to get your guidance.
Thanks！

**Comment by fperazzi** [comment]
The annotations are not in the right folder.

**Comment by EternityZY** [comment]
> The annotations are not in the right folder. Did you use `get_data.sh`to download the dataset?

I have found the problem, I am using python 3.6, the filter() function has changed, Pyhton 2.7 returns the list, and Python 3.x returns the iterator object. thank you for your reply!
