### ISSUE TITLE
error in importing module 'tstab'

### ISSUE THREAD

**Issue by InstantWindy** [fperazzi/davis-2017#15]
Hello! When I use the “t_stability.py”，it show "error in importing module 'tstab'".  (Is there a missing tstab.py here?)Thank you!

**Comment by fperazzi** [comment]
tstab is a c++ library. You have to compile the code with the provided cmake and make sure the PYTHONPATH it's pointing to the location of `tstab.so`

**Comment by InstantWindy** [comment]
Thank you! But I have a question about the "jaccard.py" file and the "f_boundary.py" file.
1. The parameters of the "db_eval_iou" function in the 'jaccard.py' file, one is the binary annotation map, and the other is the binary segmentation map. The parameter binary segmentation map refers to the network segmentation output with a threshold of 0.5 for binarization. Or is the output of the network binarized with a threshold of 0.5 after the sigmoid activation function?

2. The parameters of the 'db_eval_boundary' function in the 'f_boundary.py' file, one is the foreground_mask(binary segmentation image.) and the other is gt_mask(binary annotated image). Is the gt_mask referring to the binarization annotation? What is the foreground_mask parameter?

I am a newcomer to learning video segmentation, thank you!

**Comment by fperazzi** [comment]
If you have another question, please open a new issue related to that question. Also, please avoid to ask the same question on different repositories and and threads.
