### ISSUE TITLE
How can I evaluate my own results?

### ISSUE THREAD

**Issue by jakeoung** [fperazzi/davis-2017#2]
I am sorry if I have missed something, but I couldn't find information about evaluation of my own outputs in the script documentation.

- How should my technique directory be organized? (when I use python tools/eval.py -i path-to-my-technique -o results.yaml --year 2017 --phase val)
- Is there any guideline for segmentation format?

Many thanks,

**Comment by fperazzi** [comment]
Folder name and image name must be identical to the input, e.g. in /../path-to-my-technique/{bear,blackswam,etc..}

**Comment by Deepanshu-beep** [comment]
> 
> 
> Folder name and image name must be identical to the input, e.g. in /../path-to-my-technique/{bear,blackswan,etc..}

@fperazzi Sir can i run it in Anaconda, If not can you suggest me relevant software to run this repo. Also should me technique contain png images of masks to evaluate or any other format?
