### ISSUE TITLE
Recall Calculation

### ISSUE THREAD

**Issue by christopherhelf** [fperazzi/davis-2017#3]
Shouldn't the recall calculation in `python/lib/davis/measures/statistics.py` be

    return mean(np.array(X)>threshold)

rather than

    return mean(np.array(X)>0)

**Comment by fperazzi** [comment]
Correct it's return *mean(np.array(X)>threshold). *I just pushed the fix.
Thanks for spotting the bug.

Federico

**Comment by christopherhelf** [comment]
What a response time 👍 ! Thanks!

**Comment by InstantWindy** [comment]
@christopherhelf  Hello, Do you know the input parameters of the db_eval_boundary function in the "f_boundary.py" file? Does it refer to the predicted output of network segmentation, the real label? I am a little confused.
