### ISSUE TITLE
Evaluation result broken?

### ISSUE THREAD

**Issue by fuankarion** [fperazzi/davis-2017#4]
Hi, the  command

python tools/eval.py -i ../data/DAVIS/Results/Segmentations/480p/nlc -o  simpleTest.yaml --year 2016 --phase val

Results in:
+--------+--------+----------+---------+--------+----------+---------+
| Method | J_mean | J_recall | J_decay | F_mean | F_recall | F_decay |
+--------+--------+----------+---------+--------+----------+---------+
|  nlc   | 0.008  |  0.008   |  -0.005 | 0.008  |  0.008   |  -0.005 |
+--------+--------+----------+---------+--------+----------+---------+

I get the very same result for **any** other method in 'davis-2017/data/DAVIS/Results/Segmentations/480p',  what I find really unusual is that the command:

python tools/eval.py -i ../data/DAVIS/Annotations/480p/ -o simpleTest.yaml --year 2016 --phase val
still produces the expected (perfect) result. 

+--------+--------+----------+---------+--------+----------+---------+
| Method | J_mean | J_recall | J_decay | F_mean | F_recall | F_decay |
+--------+--------+----------+---------+--------+----------+---------+
|        | 1.000  |  1.000   |  0.000  | 1.000  |  1.000   |  0.000  |
+--------+--------+----------+---------+--------+----------+---------+

Is it now necesary to color code the predictions even for the 2016 evaluation? was this changed recently? I don't remember running into this kind of issues before

Thanks

**Comment by fperazzi** [comment]
Add --single-object. It's poorly documented, I'll add it to the README
tomorrow.

**Comment by fuankarion** [comment]
Thank you!

**Comment by fperazzi** [comment]
How did you save your images?

**Comment by fuankarion** [comment]
PNG format, same size and name as the image data
