### ISSUE TITLE
Evaluation 2017 gives me 0 for instance segmentation in all videos

### ISSUE THREAD

**Issue by mabravo641** [fperazzi/davis-2017#5]
Hi,
when I run the command 
python tools/eval.py -i ../data/DAVIS/Results/MySegmentations2017/ -o instanceTest.yaml --year 2017 --phase val

Results in:
+----------------------+--------+----------+---------+--------+----------+---------+
|        Method        | J_mean | J_recall | J_decay | F_mean | F_recall | F_decay |
+----------------------+--------+----------+---------+--------+----------+---------+
|MySegmentations2017  | 0.013  |  0.013   |  -0.022 | 0.013  |  0.013   |  -0.022 |
+----------------------+--------+----------+---------+--------+----------+---------+

My folder is organized the same way as the Annotations folder bear/00000.png etc.
and in the .yaml file I get the following results for all videos:
  bike-packing:
    F:
      decay: [0.0, 0.0]
      mean: [0.0, 0.0]
      raw:
      - [.nan, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, .nan]
      - [.nan, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, .nan]
      recall: [0.0, 0.0]
      std: [0.0, 0.0]
    J:
      decay: [0.0, 0.0]
      mean: [0.0, 0.0]
      raw:
      - [.nan, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, .nan]
      - [.nan, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, .nan]
      recall: [0.0, 0.0]
      std: [0.0, 0.0]

I get the very same result for any other method, what I find really unusual is that the command:

python tools/eval.py -i ../data/DAVIS/Annotations/480p/ -o simpleTest.yaml --year 2016 --phase val
still produces the expected (perfect) result.

+--------+--------+----------+---------+--------+----------+---------+
| Method | J_mean | J_recall | J_decay | F_mean | F_recall | F_decay |
+--------+--------+----------+---------+--------+----------+---------+
| 480p | 1.000 | 1.000 | 0.000 | 1.000 | 1.000 | 0.000 |
+--------+--------+----------+---------+--------+----------+---------+

My predictions have the same corresponding colors as the annotations but still I get the same error?

Thanks

**Comment by fperazzi** [comment]
Hi, do you think you can share your folder
../data/DAVIS/Results/MySegmentations2017/
?

Best,
Federico

**Comment by mabravo641** [comment]
Yes here is a link to my folder with the validation images segmented.
https://www.dropbox.com/s/wuyb2j81hjbdyiz/MySegmentations2017.zip?dl=0

Thanks,
Maria

**Comment by fperazzi** [comment]
Hi,

I think you did not save the images correctly. They should be saved in PNG "indexed" format. In practice, label ids + a color palette. I just added helper functions to do so. See the updated 
REAME file:

```
davis.io.imread_indexed(filename)
imwrite_indexed(filename,array).

```
See experiments/read_write_segmentation.py for usage examples

**Comment by mabravo641** [comment]
Thank you, it worked!

**Comment by zpahuja** [comment]
How did this work? Looking at the read/write code, write only accepts 2D images i.e. single channel but your PNG is RGB. I have similar problem.
