### ISSUE TITLE
Temporal stability measure (T) available?

### ISSUE THREAD

**Issue by Yuliang-Zou** [fperazzi/davis-2017#8]
Hi, I wonder if the Temporal stability measure (T) is available now? In README, it seems not yet ready, but I found the related code in the repo.

**Comment by fperazzi** [comment]
Hi, yes the code is there, but there is not plan to provide an interface
for it since it's not being used in the challenge.

If you want to evaluate the temporal stability I suggest to check out the
2016 repository.

Best,
Federico
