### ISSUE TITLE
Error in importing module 'davis'

### ISSUE THREAD

**Issue by omkar13** [fperazzi/davis-2017#9]
I receive the following error on running eval/tools.py with python 2.7: 
"ImportError: No module named davis"
Please fix the directory structure and import statements in python scripts.
Thank you.

**Comment by fperazzi** [comment]
Set the PYTHONPATH to that folder like everybody else.

Thanks

**Comment by omkar13** [comment]
I tried using sys.path.append() but received more errors. Maybe PYTHONPATH will work. Finally, I had to put all files in a single directory and modify some import statements. It was clumsily done.

**Comment by fperazzi** [comment]
Try export `PYTHONPATH=path_to_davis_2017/davis-2017/python/lib` then you should be able to `import davis` without moving files.

**Comment by omkar13** [comment]
The export statement worked. Thank you for the suggestion.

**Comment by fperazzi** [comment]
Glad!
